import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer, Header } from '@components'

const Home: NextPage = (): JSX.Element => {
	return (
		<div>
			<Head>
				<title>Setup</title>
				<meta name="description" content="Generated by Thømes setup" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<h1 className="text-6xl">Hello World!</h1>
			<Footer />
		</div>
	)
}

export default Home
